api/urls.py
from django.conf.urls import url
from .views import ProductView, CustomerList, ProductDetailView,\
    CustomerDetail, Pdfview, NestedInvoiceView, NestedInvoiceDetailView
from rest_framework.urlpatterns import format_suffix_patterns

urlpatterns = [

    url(r'^products/$', ProductView.as_view(), name='ProductView'),
    url(r'^products/(?P<pk>[\w-]+)/$', ProductDetailView.as_view(), name='ProductDetail'),


    url(r'^customers/$', CustomerList.as_view(), name='CustomerList'),
    url(r'^customers/(?P<pk>\d+)/$', CustomerDetail.as_view(), name='CustomerDetail'),


    # url(r'^invoices/$', InvoiceView.as_view(), name='invoice'),
    # url(r'^invoices/(?P<pk>[\w-]+)/$', InvoiceDetailview.as_view(), name='InvoiceDetail'),
    # url(r'^invoices/(?P<pk>[\w-]+)/$', InvoiceDetailview.as_view(), name='InvoiceUpdate'),
    url(r'^invoices/pdf/(?P<pk>[\w-]+)/$', Pdfview.as_view(), name='Invoice'),

  #  url(r'^invoicess/$', pinvoice.as_view(), name='invoice'),

    url(r'^invoices/$', NestedInvoiceView.as_view(), name="Invoices"),
    url(r'^invoices/(?P<pk>[0-9]+)/$', NestedInvoiceDetailView.as_view(), name="InvoiceDetail"),
]


urlpatterns = format_suffix_patterns(urlpatterns)

invoice_settings/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
    
    url(r'^invoicesetting/tax/$', tax, name='tax_list'),
    url(r'^invoicesetting/tax/create/$', tax_change, name='tax_create'),
    url(r'^invoicesetting/tax/edit/(?P<slug>.+)/$', tax_change, name='edit_tax'),
    url(r'^invoicesetting/tax/delete/(?P<pk>\d+)/$', tax_delete, name='tax_delete'),
    
    
    url(r'^invoicesetting/currency/$', currency, name='currency_list'),
    url(r'^invoicesetting/currency/create/$', currency_change, name='currency_create'),
    url(r'^invoicesetting/currency/edit/(?P<slug>.+)/$', currency_change, name='edit_currency'),
    url(r'^invoicesetting/currency/delete/(?P<pk>\d+)/$', currency_delete, name='currency_delete'),




    url(r'^invoicesetting/gst/$', gst, name='gst_list'),
    url(r'^invoicesetting/gst/create/$', gst_change, name='gst_create'),
    url(r'^invoicesetting/gst/edit/(?P<slug>.+)/$', gst_change, name='edit_gst'),
    url(r'^invoicesetting/gst/delete/(?P<pk>\d+)/$', gst_delete, name='gst_delete'),
    url(r'^invoicesetting/(?P<slug>.+)/add/$', invoice_template_add, name='invoice_template_add'),
    url(r'^invoicesetting/(?P<slug>.+)/$', invoice_template, name='invoice_template'),

]

payinvoice/urls.py
from django.urls import include, path
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^', include('mailprocess.urls')),
    url(r'^', include('accounts.urls')),
    url(r'^', include('myadmin.urls')),
    url(r'^', include('coupons.urls')),
    url(r'^mysite/', include('support.urls')),
    url(r'^mysite/', include('payment.urls')),
    url(r'^mysite/', include('invoice.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^mysite/', include('invoice_settings.urls')),
    url(r'^mysite/api/v1/', include('api.urls')),


]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

invoice_settings/models.py
from django.urls import reverse
from django.db import models
from django.db.models.base import ModelBase
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _
from django.utils.text import slugify
from mailprocess.models import *

COMPOSITE_SCHEME_CHOICES = ((0,'1% (For Traders and Manufacturers)'),(1,'5% (For Restaurant sector)'),
(2,'6% (For Suppliers of Services or Mixed Suppliers)'))
CURRENCY_CODE_CHOICES = ((0,'USD'), (1,'EUR'))
CURRENCY_SYMBOL_CHOICES = ((0, 'USD $'), (1, 'EUR €'))
DECIMAL_PLACES_CHOICES=((0, '0'), (1,'1'), (2,'2'))
FORMAT_CHOICES= ((0,'12345678'),(1,'12345678'))
TEMPLATE_CHOICES= ((0,'template'),(1,'background'))



class TaxRate(ModelBase):
    tax_name = models.CharField(max_length=50)
    rate  = models.DecimalField(max_digits=9, decimal_places=2)
    slug = models.SlugField(max_length=255, unique=True)
    def __str__(self):
        return str(self.tax_name)

    def save(self, *args, **kwargs):
        if not self.id:
            super(TaxRate, self).save(*args, **kwargs)
        self.slug = slugify(self.tax_name) + "-" + \
            str(self.user.id) + "-" + str(self.id)
        super(TaxRate, self).save(*args, **kwargs)

class GstSetting(ModelBase):
    gstin = models.CharField(max_length=15)
    gstdate = models.DateField()
    compositionscheme = models.IntegerField(choices=COMPOSITE_SCHEME_CHOICES,  default=0)
    slug = models.SlugField(max_length=255, unique=True)
    def __str__(self):
        return str(self.gstin)

    def save(self, *args, **kwargs):
        if not self.id:
            super(GstSetting, self).save(*args, **kwargs)
        self.slug = slugify(self.gstdate) + "-" + \
            str(self.user.id) + "-" + str(self.id)
        super(GstSetting, self).save(*args, **kwargs)
    

    

class Currency(ModelBase):
    currency_code = models.IntegerField(choices=CURRENCY_CODE_CHOICES,  default=0)
    currency_symbol = models.IntegerField(choices=CURRENCY_SYMBOL_CHOICES,  default=0)
    decimal_places = models.IntegerField(choices=DECIMAL_PLACES_CHOICES,  default=0)
    choose_format =  models.IntegerField(choices=FORMAT_CHOICES,  default=0)
    slug = models.SlugField(max_length=255, unique=True)

    def __str__(self):
        return str(self.currency_code)

    def save(self, *args, **kwargs):
        if not self.id:
            super(Currency, self).save(*args, **kwargs)
        self.slug = slugify(self.choose_format) + "-" + \
            str(self.user.id) + "-" + str(self.id)
        super(Currency, self).save(*args, **kwargs)

class Template(ModelBase):
    name=models.CharField(max_length=100)
    template_type = models.IntegerField(choices=TEMPLATE_CHOICES,  default=0)
    preview_image=models.ImageField(upload_to='uploads/invoice/', null=True, blank=True)
    path = models.CharField(max_length=100, null=True, blank=True)
    thumbnail=models.ImageField(upload_to='uploads/invoice/', null=True, blank=True)

    def __str__(self):
        return str(self.name)



class UserTemplate(models.Model):
    template=models.ForeignKey(Template,on_delete=models.CASCADE)
    customer= models.ForeignKey(User, on_delete=models.CASCADE, related_name="template_user")

   
    def __str__(self):
        return str(self.customer)

class NotesAndConditions(ModelBase):
    customer_notes = models.TextField()
    terms_and_conditions = models.TextField()

    def __str__(self):
        return self.customer_notes

invoice_settings/forms.py
from django import forms
from .models import *

class TaxRateForm(forms.ModelForm):
    class Meta:
        model = TaxRate
        exclude = ('user', 'status', 'severity', 'slug')

class GstSettingForm(forms.ModelForm):
    class Meta:
        model = GstSetting
        exclude = ('user', 'status', 'severity', 'slug')

class CurrencyForm(forms.ModelForm):
    class Meta:
        model = Currency
        exclude = ('user', 'status', 'severity', 'slug')  

invoice_settings/views.py
from django.shortcuts import render, redirect
from django.shortcuts import render, get_object_or_404
from .forms import *
from .models import *
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib import messages
from django.views.generic.edit import UpdateView



 #   currency add,edit, delete starts here #



def currency_change(request, slug=None):
    currencydetails=None
    if slug:
        currencydetails=Currency.objects.get(user=request.user, id= slug)
    if request.method == "POST":
        form = CurrencyForm(request.POST, instance=currencydetails)
        if form.is_valid():
            new_case = form.save(commit=False)
            new_case.user = request.user
            new_case.status = 1
            new_case.severity = 1
            new_case.active = 1
            new_case.save()
            return HttpResponseRedirect("/mysite/invoicesetting/currency/")
    template_name = "myadmin/invoice_setting/currency/add-currency.html"
    return render(request, template_name, {'cur':currencydetails, 'currencycode' : CURRENCY_CODE_CHOICES,'currencysymbol':CURRENCY_SYMBOL_CHOICES, 'decimalplaces' : DECIMAL_PLACES_CHOICES, 'formating':FORMAT_CHOICES  }) 



#currency_listing
def currency(request):
    template_name = "myadmin/invoice_setting/currency/currencylist.html"
    currency = Currency.objects.filter(user=request.user, active= True)
    return render(request, template_name, {'currency':currency})

#currency_delete
def currency_delete(request, pk):
    gstdetails = Currency.objects.get(id=pk)
    gstdetails.active = False
    gstdetails.save()
    return redirect('/mysite/invoicesetting/currency/')       


#   currency add,edit, delete ends here #






  #   tax add,edit, delete starts here #

#listing_of_taxes
def tax(request):
    template_name = "myadmin/invoice_setting/tax/taxlist.html"
    taxes = TaxRate.objects.filter(user=request.user, active= True)
    return render(request, template_name, {'taxes':taxes})


# create and update_tax
def tax_change(request, slug=None):
    taxdetails = None
    if slug:
        taxdetails = TaxRate.objects.get(user=request.user, id=slug)  

    if request.method == "POST":
        form = TaxRateForm(request.POST, instance=taxdetails)
        if form.is_valid():
            new_case = form.save(commit=False)
            new_case.user = request.user
            new_case.status = 1
            new_case.severity = 1
            new_case.active = 1
            new_case.save()
            return HttpResponseRedirect("/mysite/invoicesetting/tax/")
    else:
        template_name = "myadmin/invoice_setting/tax/add-tax.html"
        return render(request, template_name, {'tax' : taxdetails} )

#delate_tax
def tax_delete(request, pk):
    taxdetails = TaxRate.objects.get(id=pk)
    taxdetails.active = False
    taxdetails.save()
    return redirect('/mysite/invoicesetting/tax/') 


 #   tax add,edit, delete ends here #



#   gst add,edit,delate starts here #
       

def gst(request):
    template_name = "myadmin/invoice_setting/gst/gstlist.html"
    gstdetails = GstSetting.objects.filter(user=request.user, active= True)
    return render(request, template_name, {'gstdetails':gstdetails})


def gst_change(request, slug=None):
    gstdetails = None
    if slug:
     gstdetails = GstSetting.objects.get(user=request.user, id=slug)    

    if request.method == "POST":
        form = GstSettingForm(request.POST, instance=gstdetails)
        if form.is_valid():
            new_case = form.save(commit=False)
            new_case.user = request.user
            new_case.status = 1
            new_case.severity = 1
            new_case.active = 1
            new_case.save()
            return HttpResponseRedirect("/mysite/invoicesetting/gst/")
    else:
        template_name = "myadmin/invoice_setting/gst/add-gst.html"
        return render(request, template_name, {'gst' : gstdetails, 'compositescheme':COMPOSITE_SCHEME_CHOICES} ) 



def gst_delete(request, pk):
    gstdetails = GstSetting.objects.get(id=pk)
    gstdetails.active = False
    gstdetails.save()
    return redirect('/mysite/invoicesetting/gst/')    

#   gst add,edit, delete ends here #


def invoice_template(request, slug=None):
    template = Template.objects.filter(active=True)
    # import pdb; pdb.set_trace()
    template_type_var=0
    if slug=='template':
        template=template.filter(template_type=0)
       
    else:
        template=template.filter(template_type=1)
        template_type_var=1

    try:
        usertemplate=UserTemplate.objects.get(customer=request.user, template__template_type=template_type_var)
        
    except:
        usertemplate=None
    template_name ='myadmin/invoice_setting/invoice_template.html'
    return render(request,template_name, {'templates':template, 'usertemplate':usertemplate},)


def invoice_template_add(request, slug=None):
    template_id = request.GET.get("template_id")
    # import pdb; pdb.set_trace()
    template_type_var=0
    if slug !='template':
        template_type_var=1
    if template_id:
        template= Template.objects.get(id=template_id)
        try:
            usertemplate=UserTemplate.objects.get(customer=request.user, template__template_type=template_type_var)
            usertemplate.template=template
            usertemplate.save()
        except:
            usertemplate=UserTemplate()
            usertemplate.customer=request.user
            usertemplate.template=template
            usertemplate.save()
    return HttpResponseRedirect("/mysite/invoicesetting/"+slug+"/")
   

templates/myadmin/invoice_setting/currency/add-currency.html
{% extends "admin_base.html" %}
{% block title %} Add Currency {% endblock %}

{% block content-wrapper %}


<div class="content-wrapper" style="min-height: 903px;">
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <h1>
      Add Currency
    </h1>
    <ol class="breadcrumb">
      <li><a href="/mysite/"><i class="fa fa-dashboard"></i> Home</a></li>
      <li><a href="/mysite/invoicesetting/currency/">My Currency</a></li>
    </ol>
  </section>

  <!-- Main content -->
  <section class="content">
    <div class="row">
      <!-- right column -->
      <div class="col-md-12">
        <!-- Horizontal Form -->
        <div class="box box-info">
          <div class="box-header with-border">
            <h3 class="box-title">Currency Details</h3>
          </div>
          <!-- /.box-header -->
          <!-- form start -->
          <form class="form-horizontal" id="gstform" name="gstform" method="POST" action="">
            {% csrf_token %}

            <div class="box-body">
              <div class="form-group">
                <div class="col-sm-offset-3 col-sm-9">
                  <span class="error-message error" style="display:none">

                  </span>
                </div>
              </div>



              <div class="form-group">
                <label class="col-sm-3 control-label" for="currency_code">Currency Code</label>
                <div class="col-sm-9">
                  <select class="form-control" id="currency_code" name="currency_code" required>
                    {% for c in currencycode %}
                    <option value="{{ c.0 }}" {% ifequal c.0 cur.currency_code %} selected="selected" {% endifequal %}>
                      {{ c.1 }}</option>

                    {% endfor %}
                  </select>
                </div>
              </div>

              <div class="form-group">
                <label class="col-sm-3 control-label" for="currency_symbol">Currency Symbol</label>
                <div class="col-sm-9">
                  <select class="form-control" id="currency_symbol" name="currency_symbol" required>
                    {% for c in currencysymbol %}
                    <option value="{{ c.0 }}" {% ifequal c.0 cur.currency_symbol %} selected="selected" {% endifequal %}>
                      {{ c.1 }}</option>

                    {% endfor %}
                  </select>
                </div>
              </div>

              <div class="form-group">
                <label class="col-sm-3 control-label" for="decimal_places">Decimal Places</label>
                <div class="col-sm-9">
                  <select class="form-control" id="decimal_places" name="decimal_places" required>
                    {% for c in decimalplaces %}
                    <option value="{{ c.0 }}" {% ifequal c.0 cur.decimal_places %} selected="selected" {% endifequal %}>
                      {{ c.1 }}</option>

                    {% endfor %}
                  </select>
                </div>
              </div>

              <div class="form-group">
                <label class="col-sm-3 control-label" for="choose_format">Choose Format</label>
                <div class="col-sm-9">
                  <select class="form-control" id="choose_format" name="choose_format" required>
                    {% for c in formating %}
                    <option value="{{ c.0 }}" {% ifequal c.0 cur.choose_format %} selected="selected" {% endifequal %}>
                      {{ c.1 }}</option>

                    {% endfor %}

                  </select>
                </div>
              </div>

              <!-- /.box-body -->
              <div class="box-footer">
                <button class="btn btn-default" type="reset">Reset</button>
                <button class="btn btn-info pull-right" type="submit" id="sender_button">Add</button>
              </div>
              <!-- /.box-footer -->
          </form>
        </div>
        <!-- /.box -->
      </div>
      <!--/.col (right) -->
    </div>
    <!-- /.row -->
  </section>



  <!-- /.content -->
</div>
<!-- /.content-wrapper -->

{% endblock %}

templates/myadmin/invoice_setting/currency/currencylist.html
{% extends "admin_base.html" %}
{% block title %} Your Currency || Dashboard {% endblock %}
{% block content-wrapper %}

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">


    <section class="content-header">
        <h1>
            Currency
        </h1>
        <ol class="breadcrumb">
            <li><a href="/mysite/"><i class="fa fa-dashboard"></i> Home</a></li>
            <li class="active">Currency</li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content">
        <!-- Info boxes -->
        <div class="row">
            <!-- Left col -->
            <section class="col-sm-12 connectedSortable ui-sortable">
                <!-- Custom tabs (Charts with tabs)-->

                <!-- /.nav-tabs-custom -->

                <!-- Chat box -->

                <!-- /.box (chat box) -->

                <!-- TO DO List -->
                
                <div class="box box-primary">
                    {% if currency %}
                    <div class="box-header ui-sortable-handle" style="cursor: move;">

                        <h3 class="box-title"> Currency Details</h3>
                        <a href="/mysite/invoicesetting/currency/create/" class="pull-right btn btn-primary">
                            <i class="fa fa-plus-circle"></i>
                            <h3 class="box-title">Add Currency</h3>
                        </a>
                    </div>
                    {% else %}
                    <div class="box-header ui-sortable-handle" style="cursor: move;">

                        <h3 class="box-title"> Currency Details</h3>
                        <a href="/mysite/invoicesetting/currency/create/" class="pull-right btn btn-primary">
                            <i class="fa fa-plus-circle"></i>
                            <h3 class="box-title">Add Currency</h3>
                        </a>
                    </div>

                    {% endif %}
                        <!-- /.box-header -->
                        <div class="box-body no-padding">

                            <table class="table">
                                <tbody>
                                    {% if currency %}
                                    <tr>
                                        <th>Currency Code</th>
                                        <th>Currency Symbol</th>
                                    </tr>
                                    {% for currency in currency %}
                                    <tr>

                                        <td>
                                            {{ currency.get_currency_code_display }}
                                        </td>
                                        <td>
                                            {{ currency.get_currency_symbol_display }}
                                        </td>
                                        <td><div>
                                            <a href="/mysite/invoicesetting/currency/edit/{{currency.id}}/" style="color: inherit"><i class="fa fa-edit"></i></a>
                                            <a style="color:inherit" href="/mysite/invoicesetting/currency/delete/{{currency.id}}/"
                                              onclick="return confirm('Are you sure?')"><i class="fa fa-trash-o"></i></a>
                                          </td></div>
                                        

                                    </tr>
                                    {% endfor %}
                                    {% else %}
                                    <tr>
                                        <td>
                                            No currency found.
                                        </td>
                                    </tr>
                                    {% endif %}


                                </tbody>
                            </table>
                        </div>
                        <!-- /.box-body -->

                    </div>
                    <!-- /.box -->

                    <!-- quick email widget -->


            </section>
            <!-- /.Left col -->
            <!-- right col (We are only adding the ID to make the widgets sortable)-->

            <!-- right col -->
        </div>
        <!-- /.row -->


    </section>




    <!-- /.content -->
</div>
<!-- /.content-wrapper -->





{% endblock %}