api/urls.py
from django.conf.urls import url
from .views import ProductView, CustomerList, ProductDetailView,\
    CustomerDetail, Pdfview, NestedInvoiceView, NestedInvoiceDetailView
from rest_framework.urlpatterns import format_suffix_patterns

urlpatterns = [

    url(r'^products/$', ProductView.as_view(), name='ProductView'),
    url(r'^products/(?P<pk>[\w-]+)/$', ProductDetailView.as_view(), name='ProductDetail'),


    url(r'^customers/$', CustomerList.as_view(), name='CustomerList'),
    url(r'^customers/(?P<pk>\d+)/$', CustomerDetail.as_view(), name='CustomerDetail'),


    # url(r'^invoices/$', InvoiceView.as_view(), name='invoice'),
    # url(r'^invoices/(?P<pk>[\w-]+)/$', InvoiceDetailview.as_view(), name='InvoiceDetail'),
    # url(r'^invoices/(?P<pk>[\w-]+)/$', InvoiceDetailview.as_view(), name='InvoiceUpdate'),
    url(r'^invoices/pdf/(?P<pk>[\w-]+)/$', Pdfview.as_view(), name='Invoice'),

  #  url(r'^invoicess/$', pinvoice.as_view(), name='invoice'),

    url(r'^invoices/$', NestedInvoiceView.as_view(), name="Invoices"),
    url(r'^invoices/(?P<pk>[0-9]+)/$', NestedInvoiceDetailView.as_view(), name="InvoiceDetail"),
]


urlpatterns = format_suffix_patterns(urlpatterns)

invoice/urls.py
from django.conf.urls import url
from .views import *


urlpatterns = [
    url(r'^product/add/$', product_change, name="add"),
    url(r'^product/update/(?P<slug>.+)/$', product_change, name="update"),
    url(r'^product/delete/(?P<pk>\d+)/$', delete_page, name="delete"),
    url(r'^product/detail/(?P<slug>.+)/$', detail_page, name="detail"),
    url(r'^product/$', list_page, name="listing"),


    url(r'^customer/add/$', customer_change, name="add_customer"),
    url(r'^customer/$', customer_list, name="listing"),
    url(r'^customer/detail/(?P<pk>\d+)/$', customer_detail, name="detail_customer"),
    url(r'^customer/delete/(?P<pk>\d+)/$', customer_delete, name="delete_customer"),
    url(r'^customer/update/(?P<slug>.+)/$', customer_change, name="update_customer"), 

    url(r'^invoice/$', invoice, name='invoice_list'),
    url(r'^invoice/create/$', invoice_change, name='invoice_create'),
    url(r'^invoice/update/(?P<pk>\d+)/$', invoice_change, name='update_invoice'),
    url(r'^invoice/detail/(?P<pk>\d+)/$', invoice_detail, name='detail_invoice'),
    url(r'^invoice/delete/(?P<pk>\d+)/$', invoice_delete, name='delete_invoice'),

]

payinvoice/urls.py
from django.urls import include, path
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^', include('mailprocess.urls')),
    url(r'^', include('accounts.urls')),
    url(r'^', include('myadmin.urls')),
    url(r'^', include('coupons.urls')),
    url(r'^mysite/', include('support.urls')),
    url(r'^mysite/', include('payment.urls')),
    url(r'^mysite/', include('invoice.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^mysite/', include('invoice_settings.urls')),
    url(r'^mysite/api/v1/', include('api.urls')),


]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

invoice/models.py
from django.db import models
from django.db.models.base import ModelBase
from django.utils.text import slugify
from mailprocess.models import *

PAYMENT_TERMS_CHOICE = (
    (0, 'NET15'), (1, 'NET30'), (2, 'NET45'), (3, 'NET60'), (4, 'Due end of the month'), (5, 'Due end of next month'))
LANGUAGE_CHOICES = ((0, 'English'),)
CURRENCY_CHOICES = (
    (0, 'AUD- Australian Dollar'), (1, 'CAD- Canadian Dollar'), (2, 'EUR- Euro'), (3, 'INR- Indian Rupee'),
    (4, 'USD- United States Dollar'), (5, 'SAR- Saudi Riyal'))
UNIT_CHOICES = ((0, 'm'), (1, 'cm'), (2, 'gm'), (3, 'kg'), (4, 'pc'), (5, 'dozen'), (6, 'units'))
TERMS_CHOICES = (
    (0, 'NET15'), (1, 'NET30'), (2, 'NET45'), (3, 'NET60'), (4, 'Due end of the month'), (5, 'Due end of next month'),
    (6, 'Due on Receipt'), (7, 'Custom'))
CHALLAN_TYPE_CHOICES = ((0, 'supply of liquid gas'), (1, 'job work'), (2, 'supply on approval'), (3, 'other'))
PRODUCT_TYPE_CHOICES = ((0, 'Goods'), (1, 'Services'))
CUSTOMER_CHOICE = ((1, "Business"), (2, "Individual"))
DISCOUNT_UNIT = ((0, '%'), (1, 'Amount'))
STATUS_CHOIES = ( (1,"draft"), (3,"paid"), (5,"sent"))

class Customers(ModelBase):
    customer_type = models.IntegerField(choices=CUSTOMER_CHOICE, default=0)
    first_name = models.CharField(max_length=100, null=True, blank=True)
    last_name = models.CharField(max_length=100, null=True, blank=True)
    company_name = models.CharField(max_length=100, null=True, blank=True)
    email = models.EmailField()
    phone = models.CharField(max_length=20, null=True, blank=True)
    website = models.CharField(max_length=200, null=True, blank=True)
    billing_country = models.ForeignKey(Country, on_delete=models.CASCADE, null=True, blank=True)
    billing_state = models.CharField(max_length=200, null=True, blank=True)
    billing_city = models.CharField(max_length=200, null=True, blank=True)
    billing_zipcode = models.CharField(max_length=12, null=True, blank=True)
    billing_address = models.CharField(max_length=200, null=True, blank=True)
    currency = models.IntegerField(choices=CURRENCY_CHOICES, default=0)
    payment_terms = models.IntegerField(choices=PAYMENT_TERMS_CHOICE, default=0)
    enable_portal = models.BooleanField(default=False)
    portal_language = models.IntegerField(choices=LANGUAGE_CHOICES, default=0)
    shipping_country = models.ForeignKey(Country, on_delete=models.CASCADE, null=True, blank=True,
                                         related_name='shipping')
    shipping_state = models.CharField(max_length=150, null=True, blank=True)
    shipping_city = models.CharField(max_length=150, null=True, blank=True)
    shipping_zipcode = models.CharField(max_length=14, null=True, blank=True)
    shipping_address = models.CharField(max_length=150, null=True, blank=True)
    slug = models.SlugField(max_length=250, unique=True)

    def save(self, *args, **kwargs):
        if not self.id:
            super(Customers, self).save(*args, **kwargs)
        self.slug = slugify(self.first_name) + "-" + str(self.id)
        super(Customers, self).save(*args, **kwargs)


class Products(ModelBase):
    product_type = models.IntegerField(choices=PRODUCT_TYPE_CHOICES, default=0)
    name = models.CharField(max_length=256)
    unit = models.IntegerField(choices=UNIT_CHOICES, default=0)
    selling_price = models.DecimalField(max_digits=9, decimal_places=2)
    sku = models.CharField(max_length=100, null=True, blank=True)
    product_image = models.ImageField(upload_to='upload/products/', null=True, blank=True)
    description = models.CharField(max_length=200, null=True, blank=True)
    slug = models.SlugField(max_length=250, unique=True)

    def save(self, *args, **kwargs):
        if not self.id:
            super(Products, self).save(*args, **kwargs)

        self.slug = slugify(self.name) + "-" + str(self.user.id) + "-" + str(self.id)

        super(Products, self).save(*args, **kwargs)

    def __str__(self):
        return str(self.name)


class Invoices(ModelBase):
    customer = models.ForeignKey(Customers, related_name='invoice_customer', on_delete=models.CASCADE, )
    invoice_number = models.CharField(max_length=100)
    order_number = models.CharField(max_length=100, null=True, blank=True)
    invoice_date = models.DateField()
    terms = models.IntegerField(choices=TERMS_CHOICES, default=0)
    due_date = models.DateField()
    subject = models.CharField(max_length=200, null=True, blank=True)
    subtotal = models.DecimalField(max_digits=9, decimal_places=2)
    total = models.DecimalField(max_digits=9, decimal_places=2)
    pdf_code = models.TextField(max_length=250, null=True, blank=True)
    status = models.IntegerField(choices=STATUS_CHOIES, default=1)

    # customer_notes = models.CharField(max_length=200, null=True, blank=True)
    # terms_and_conditions = models.TextField()  #moved it to invoice settings


class ProductInvoice(models.Model):
    products = models.ForeignKey(Products, related_name='product', on_delete=models.CASCADE, )
    invoices = models.ForeignKey(Invoices, related_name='productinvoices', on_delete=models.CASCADE,)
    quantity = models.DecimalField(max_digits=9, decimal_places=2)
    rate = models.DecimalField(max_digits=9, decimal_places=2)
    discount = models.DecimalField(max_digits=9, decimal_places=2)
    discount_unit = models.IntegerField(choices=DISCOUNT_UNIT, default=1)
    amount = models.DecimalField(max_digits=9, decimal_places=2)
    slug = models.SlugField(max_length=255, unique=True)
    active = models.BooleanField(default=True)


    # def save(self, *args, **kwargs):
    #     if not self.id:
    #         super(ProductInvoice, self).save(*args, **kwargs)
    #
    #     self.slug = slugify(self.amount) + "-" + str(self.invoices.user.id) + "-" + str(self.id)
    #
    #     super(ProductInvoice, self).save(*args, **kwargs)


'''class DeliveryChallan(ModelBase):
    customer_name=models.ForeignKey(Customers,on_delete=models.CASCADE)
    delivery_challan_number=models.CharField(max_length=20)
    reference_number=models.CharField(max_length=20, null=True, blank=True)
    delivery_challan_date=models.DateField()
    challan_type=models.IntegerField(choices=CHALLAN_TYPE_CHOICES,default=0)
    product_details=models.ForeignKey(Products,on_delete=models.CASCADE)
    quantity=models.CharField(max_length=200, null=True, blank=True)
    rate=models.DecimalField(max_digits=9,decimal_places=2)
    discount=models.DecimalField(max_digits=9,decimal_places=2)
    amount=models.DecimalField(max_digits=9,decimal_places=2)
    subtotal=models.DecimalField(max_digits=9,decimal_places=2)
    total=models.DecimalField(max_digits=9,decimal_places=2)
    customer_notes=models.CharField(max_length=200, null=True, blank=True)
    terms_and_conditions=models.TextField()'''

product/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from mailprocess.models import ModelBase


class Product(ModelBase):
    name = models.CharField(max_length=100, null=True, blank=True)

    active = models.BooleanField(default=0)
    is_addon = models.BooleanField(default=0)
    def __str__(self):
        return str(self.name)

invoice/views.py
from django.shortcuts import render, redirect
from django.shortcuts import render, get_object_or_404
from .forms import *
from .models import *
from django.contrib import messages
from django.views.generic.edit import UpdateView
from django.http import HttpResponse, HttpResponseRedirect

from .forms import ProductForm, CustomerForm, ProductInvoiceForm
from .models import Products, PRODUCT_TYPE_CHOICES, UNIT_CHOICES, Customers, CUSTOMER_CHOICE, CURRENCY_CHOICES, \
    PAYMENT_TERMS_CHOICE, LANGUAGE_CHOICES, STATUS_CHOIES
from mailprocess.models import Country
from invoice_settings.models import NotesAndConditions




def invoice(request):
    template_name = "myadmin/invoice/invoicelist.html"
    qs = Invoices.objects.filter(user=request.user, active= True)
    invoice_number_query = request.GET.get('invoice_number')
    invoice_date_query = request.GET.get('invoice_date')
    due_date_query = request.GET.get('due_date')

    if invoice_number_query != "" and  invoice_number_query is not None:
        qs = qs.filter(invoice_number__iexact=invoice_number_query)

    elif invoice_date_query != "" and  invoice_date_query is not None:
        qs = qs.filter(invoice_date__iexact=invoice_date_query)

    elif due_date_query != "" and  due_date_query is not None:
        qs = qs.filter(due_date__iexact=due_date_query)    

    context = {
        'inv': qs
    }   
    return render(request, template_name, context )


# def invoice_change(request, slug=None):
#     invoicedetails=None
#     if slug:
#         invoicedetails=ProductInvoice.objects.get(user=request.user, slug= slug)
#     if request.method == "POST":
#         form = ProductInvoiceForm(request.POST, instance=invoicedetails)
#         if form.is_valid():
#             new_upload = form.save(commit=False)
#             new_upload.user = request.user
#             new_upload.active = 1
#             new_upload.severity = 1
#             new_upload.status = 1
#             new_upload.save()
#             return HttpResponseRedirect("/mysite/mysite/invoice/")
#     template_name = "myadmin/invoice/add-invoice.html"
#     return render(request, template_name, {'invoicedetails':invoicedetails})

def invoice_change(request, pk=None):
    invoice_data = None
    pinvoice_data = None
    note_condition = NotesAndConditions.objects.get(user=request.user)

    if pk:
        invoice_data = Invoices.objects.get(user=request.user, id=pk)
    if invoice_data:
        pinvoice_data = ProductInvoice.objects.filter(invoices=invoice_data)

    if request.method == "POST":
        invoice_form = InvoiceForm(request.POST, instance=invoice_data)
        pinvoice_form = ProductInvoiceForm(request.POST, instance=pinvoice_data)
        if invoice_form.is_valid() and pinvoice_form.is_valid():
            inv = invoice_form.save(commit=False)
            print(inv)
            pinv = pinvoice_form.save(commit=False)
            inv.user = request.user
            inv.active = 1
            inv = inv.save()
            inv_obj = Invoices.objects.get(id=inv.id)
            if inv_obj:
                print(inv_obj.customer.name)
                pinv.invoices = inv_obj.id
                pinv.active = 1
                pinv.save()
                return HttpResponseRedirect("/mysite/invoice/")
            else:
                print("Invoice is not getting through database")
    template_name = "myadmin/invoice/add-invoice.html"
    return render(request, template_name, {'invoice_data': invoice_data,
                                           'pinvoice_data': pinvoice_data,
                                           'products': Products.objects.all(),
                                           'customers': Customers.objects.all(),
                                           'status_choices': STATUS_CHOIES,
                                           'note_condition':note_condition},)


def invoice_detail(request, pk):
    invoice_obj = Invoices.objects.get(user=request.user, id=pk)
    pinvoice_obj = ProductInvoice.objects.filter(invoices=invoice_obj)
    template_name = "myadmin/invoice/invoice_detail.html"
    return render(request,template_name, {'invoice_obj': invoice_obj, "pinvoice_obj": pinvoice_obj})


def invoice_delete(request, pk):
    obj = Invoices.objects.get(user=request.user, id=pk)
    obj.active = False
    obj.save()
    return redirect('/mysite/invoice/')



def product_change(request, slug=None):
    obj = None
    if slug:
        obj = Products.objects.get(user=request.user, slug=slug)
    if request.method == "POST":
        form = ProductForm(request.POST, instance=obj)
        if form.is_valid():
            new_upload = form.save(commit=False)
            new_upload.user = request.user
            new_upload.active = 1
            new_upload.severity = 1
            new_upload.status = 1
            new_upload.save()
            return HttpResponseRedirect('/mysite/product/')

    else:
        return render(request, "myadmin/invoice/product/product.html", {'obj': obj,
                                                        'product_type': PRODUCT_TYPE_CHOICES,
                                                        'unit': UNIT_CHOICES})


def list_page(request):
    obj = Products.objects.filter(user=request.user, active=True)
    template_name = "myadmin/invoice/product/list.html"
    return render(request, template_name, {'obj': obj})


def detail_page(request, slug):
    obj = Products.objects.get(user=request.user, slug=slug)
    template_name = "myadmin/invoice/product/detail.html"
    return render(request,template_name, {'obj': obj})


def delete_page(request, pk):
    obj = Products.objects.get(id=pk)
    obj.active = False
    obj.save()
    return redirect('/mysite/product/')


def customer_change(request, slug=None):
    customerdetails = None
    if slug:
        customerdetails = Customers.objects.get(user=request.user, slug=slug)

    if request.method == "POST":
        form = CustomerForm(request.POST, instance=customerdetails)
        if form.is_valid():
            new_case = form.save(commit=False)
            new_case.user = request.user
            new_case.status = 1
            new_case.severity = 1
            new_case.active = 1
            new_case.save()
            return HttpResponseRedirect('/mysite/customer/')

    template_name = "myadmin/invoice/customer/customer.html"
    return render(request, template_name, {'customerdetails': customerdetails,
                                           'customer_type': CUSTOMER_CHOICE,
                                           'currency': CURRENCY_CHOICES,
                                           'payment_terms': PAYMENT_TERMS_CHOICE,
                                           'country': Country.objects.all(),
                                           'portal_language': LANGUAGE_CHOICES})


def customer_list(request):
    obj = Customers.objects.filter(user=request.user, active=True)
    template_name = "myadmin/invoice/customer/list.html"
    return render(request, template_name, {'obj': obj})


def customer_detail(request, pk):
    obj = Customers.objects.get(user=request.user, id=pk)
    template_name = "myadmin/invoice/customer/detail.html"
    return render(request, template_name, {'obj': obj})


def customer_delete(request, pk):
    obj = Customers.objects.get(user=request.user, id=pk)
    obj.active = False
    obj.save()
    return redirect('/mysite/customer/')

templates/myadmin/invoice/product/detail.html
{% extends "admin_base.html" %}
{% block title %} Product Detail {% endblock %}
{% load staticfiles %}

{% block content-wrapper %}

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Product Details
        </h1>
        <ol class="breadcrumb">
            <li><a href="/mysite/"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="/invoice/listing/">Product List</a></li>
            <li>Product Details</li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content">

        <div class="row">
            <div class="col-md-12">
                <div class="box box-primary">
                    <div class="box-header with-border">

                        <h3 class="box-title">Product Detail</h3>
                        <span class="pull-right">
                           {% if obj.status != 4 %}<a class=""
                                                        href="#"></a>
                            <a class="btn btn-success btn-sm" href="/mysite/product/update/{{obj.slug}}">Edit</a>{% endif %}
                            <a class="btn btn-sm btn-danger" href="/mysite/product/delete/{{obj.id}}/">Delete</a>
                     </span>
                    </div>


                    <div class="box-body no-padding">
                        <table class="table">


                            <tr>
                                <td><b>Product Type</b></td>
                                <td>{{ obj.get_product_type_display }}</td>
                            </tr>
                            <tr>
                                <td><b>Name</b></td>
                                <td>{{ obj.name }}</td>
                            </tr>
                            <tr>{% if obj.Units != 0 %}
                                <td><b>Units</b></td>
                                <td>{{ obj.get_unit_display }}</td>
                                {% endif %}
                            </tr>
                            <tr>{% if obj.Sku != 0 %}
                                <td><b>Sku</b></td>
                                <td>{{ obj.sku }}</td>
                                {% endif %}
                            </tr>
                            <tr>
                                <td><b>Selling Price</b></td>
                                <td>{{ obj.selling_price}}</td>

                            </tr>
                            <tr>
                                <td><b>Description</b></td>
                                <td>{{ obj.description}}</td>

                            </tr>


                        </table>
                     </div>




                </div>
            </div>
        </div>

        <!-- /.row -->

    </section>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->

{% endblock %}

templates/myadmin/invoice/product/list.html
{% extends "admin_base.html" %}
{% block title %} Product List {% endblock %}
{% block content-wrapper %}
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Product
        </h1>
        <ol class="breadcrumb">
            <li><a href="/mysite/"><i class="fa fa-dashboard"></i> Home</a></li>
            <li class="active">Product</li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content">
        <!-- Info boxes -->
        <div class="row">
            <div class="col-md-12">
                <div class="box">
                    <div class="box-header">

                        <a class="pull-right btn btn-xs btn-primary" href="/mysite/product/add/"><i class="fa fa-plus"></i>
                            <h3 class="box-title" style="font-size:22px !important;"> Add</h3></a>

                        <div class="box-tools">
                        </div>
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body no-padding">
                        <table class="table">
                            <tbody>
                            <tr>
                                <th>Product Type </th>
                                <th>Product Name </th>
                                <th>Unit</th>
                                <th>Selling Price</th>
                            </tr>
                            {% for product in obj %}
                            <tr>
                                <td>{{ product.get_product_type_display}}</td>
                                <td>{{ product.name }}</td>
                                <td>{{ product.get_unit_display }}</td>
                                <td>{{ product.selling_price }}</td>
                                <td>
                                    <div class="tools">
                                        <a style="color:inherit"
                                           href="/mysite/product/detail/{{product.slug}}/"
                                           target="_blank"><i class="fa fa-eye"></i></a>
                                        <a href="/mysite/product/update/{{product.slug}}/"
                                           style="color: inherit"><i class="fa fa-edit"></i></a>
                                        <a style="color:inherit"
                                           href="/mysite/product/delete/{{product.id}}/"
                                           onclick="return confirm('Are you sure?')"><i class="fa fa-trash-o"></i></a>

                                    </div>

                                </td>
                            </tr>
                            {% empty %}
                            <tr>
                                <td colspan="9">No Product Found.</td>
                            </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                    <!-- /.box-body -->
                </div>
                <!-- /.box -->
            </div>
        </div>
        <!-- /.row -->


    </section>
    </div>
{% endblock %}

templates/myadmin/invoice/product/product.html
{% extends "admin_base.html" %}

{% block title %} PRODUCTS {% endblock %}
{% load staticfiles %}
{% block content-wrapper %}

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Products
        </h1>
        <ol class="breadcrumb">
            <li><a href="/mysite/"><i class="fa fa-dashboard"></i> Home</a></li>
            <li class="active">Product</li>
        </ol>
    </section>
    <!-- Main content -->
    <section class="content">
        <div class="row">

            <!-- right column -->
            <div class="col-md-12">
                <div class="box-body no-padding">
                    <div class="box-header with-border">
                        <table class="table">


                            <div class="box box-primary">
                                <div class="box-header with-border">
                                    <!-- /.box-header -->
                                    <form method="post" action="{% if obj  %}/mysite/product/update/{{ obj.slug }}/{% else %}/mysite/product/add/{% endif %}">
                                        {% csrf_token %}
                                        <div class="col-md-6">


                                            <div class="form-group">
                                                <label class="control-label" for="name"> Name*</label>
                                                <input type="text" class="form-control" id="name" name="name" placeholder=" Name" value="{{ obj.name }}" >
                                            </div>

                                            <div class="form-group">
                                                <label class="control-label" for="product_type">Product Type</label>
                                                <select class="form-control" id="product_type"  name="product_type">
                                                    {% for c in product_type %}
                                                    <option value="{{ c.0 }}" {% ifequal c.0 obj.product_type %}
                                                            selected="selected" {% endifequal %}>{{ c.1 }}
                                                    </option>
                                                    {% endfor %}
                                                </select>
                                                <!--                        <input type="text" class="form-control" id="product_type" name="product_type" placeholder="Product Type" value="{{ customerdetails.first_name }}" >-->
                                            </div>

                                            <div class="form-group">
                                                <label class="control-label" for="selling_price">Selling Price</label>
                                                <input type="text" class="form-control" id="selling_price" name="selling_price" placeholder="Selling Price" value="{{ obj.selling_price }}" >
                                            </div>

                                            <div class="form-group">
                                                <label class="control-label" for="sku">SKU</label>
                                                <input type="text" class="form-control" id="sku" name="sku" placeholder="SKU" value="{{ obj.sku }}" >
                                            </div>

                                            <div class="form-group">
                                                <label class="control-label" for="unit">Unit</label>
                                                <select class="form-control" id="unit"  name="unit">
                                                    {% for c in unit %}
                                                    <option value="{{ c.0 }}" {% ifequal c.0 obj.product_type %}
                                                            selected="selected" {% endifequal %}>{{ c.1 }}
                                                    </option>
                                                    {% endfor %}
                                                </select>
                                                <!--                  <input type="text" class="form-control" id="unit" name="unit" placeholder="unit" value="{{ customerdetails.first_name }}" >-->
                                            </div>

                                            <div class="form-group">
                                                <label class="control-label" for="description">Description</label>
                                                <input type="text" class="form-control" id="description" name="description" placeholder="Description" value="{{obj.description }}" >
                                            </div>
                                            <button type="submit" class="btn btn-primary">Submit</button>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </table>
                    </div>
                </div>
                
            </div>
        </div>

</section>

</div>

{% endblock %}