api/urls.py
from django.conf.urls import url
from .views import ProductView, CustomerList, ProductDetailView,\
    CustomerDetail, Pdfview, NestedInvoiceView, NestedInvoiceDetailView
from rest_framework.urlpatterns import format_suffix_patterns

urlpatterns = [

    url(r'^products/$', ProductView.as_view(), name='ProductView'),
    url(r'^products/(?P<pk>[\w-]+)/$', ProductDetailView.as_view(), name='ProductDetail'),


    url(r'^customers/$', CustomerList.as_view(), name='CustomerList'),
    url(r'^customers/(?P<pk>\d+)/$', CustomerDetail.as_view(), name='CustomerDetail'),


    # url(r'^invoices/$', InvoiceView.as_view(), name='invoice'),
    # url(r'^invoices/(?P<pk>[\w-]+)/$', InvoiceDetailview.as_view(), name='InvoiceDetail'),
    # url(r'^invoices/(?P<pk>[\w-]+)/$', InvoiceDetailview.as_view(), name='InvoiceUpdate'),
    url(r'^invoices/pdf/(?P<pk>[\w-]+)/$', Pdfview.as_view(), name='Invoice'),

  #  url(r'^invoicess/$', pinvoice.as_view(), name='invoice'),

    url(r'^invoices/$', NestedInvoiceView.as_view(), name="Invoices"),
    url(r'^invoices/(?P<pk>[0-9]+)/$', NestedInvoiceDetailView.as_view(), name="InvoiceDetail"),
]


urlpatterns = format_suffix_patterns(urlpatterns)

myadmin/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView
from .views import *

urlpatterns = [
    url(r'^mysite/$', mysite, name='mysite'),

]

payinvoice/urls.py
from django.urls import include, path
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^', include('mailprocess.urls')),
    url(r'^', include('accounts.urls')),
    url(r'^', include('myadmin.urls')),
    url(r'^', include('coupons.urls')),
    url(r'^mysite/', include('support.urls')),
    url(r'^mysite/', include('payment.urls')),
    url(r'^mysite/', include('invoice.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^mysite/', include('invoice_settings.urls')),
    url(r'^mysite/api/v1/', include('api.urls')),


]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

support/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
    url(r'^support/$', support, name='support'),
    url(r'^support/create/$', support_create, name='support-create'),
    url(r'^support/reopen/(?P<case_id>\d+)/$', support_reopen, name='support_reopen'),
    url(r'^support/detail/(?P<case_id>\d+)/$', support_detail, name='support-detail'),
]

support/models.py
from django.db import models
from django.contrib.auth.models import User
# from sites.models import Site
from product.models import Product

STATUS_CHOICE = ((1, 'OPEN'), (2, 'IN PROCESS'), (3, 'RESOLVED'), (5, 'REOPEN'), (4, 'CLOSED'))
SEVERITY_CHOICE = ((1, 'LOW'), (2, 'MEDIUM'), (3, 'HIGH'))


class SupportPlanCategory(models.Model):
    name = models.CharField(max_length=100, null=True, blank=True)
    active = models.BooleanField(default=True)
    modified_date = models.DateTimeField(auto_now=True)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.name)


class SupportCases(models.Model):
    subject = models.CharField(max_length=100)
    description = models.TextField(null=True, blank=True)
    severity = models.IntegerField(choices=SEVERITY_CHOICE, default=1)
    status = models.IntegerField(choices=STATUS_CHOICE, default=1)
    supportcategory = models.ForeignKey(SupportPlanCategory, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE, null=True, blank=True)
    active = models.BooleanField(default=True)
    modified_date = models.DateTimeField(auto_now=True)
    date = models.DateTimeField(auto_now_add=True)
    # site=models.ForeignKey(Site)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.pk)


class SupportCasesDetail(models.Model):
    supportcases = models.ForeignKey(SupportCases, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    comment = models.TextField(null=True, blank=True)
    active = models.BooleanField(default=True)
    modified_date = models.DateTimeField(auto_now=True)

support/forms.py
from django import forms
from .models import SupportCases


class SupportCasesForm(forms.ModelForm):
    class Meta:
        model = SupportCases
        exclude = ('user', 'status', 'severity')

myadmin/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.db.models import Sum
from django.conf import settings




@login_required
def mysite(request):
    template_name = "myadmin/index.html"
    return render(request, template_name, {})

support/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from .forms import SupportCasesForm
from .models import *
from django.http import HttpResponse, HttpResponseRedirect


@login_required
def support(request):
    template_name = "myadmin/support/support.html"
    supportcase = SupportCases.objects.filter(active=True, user=request.user)
    return render(request, template_name, {'supportcase': supportcase})


@login_required
def support_create(request):
    template_name = "myadmin/support/support_create.html"
    if request.method == "POST":
        form = SupportCasesForm(request.POST)
        if form.is_valid():
            new_case = form.save(commit=False)
            new_case.user = request.user
            new_case.status = 1
            new_case.severity = 1
            new_case.active = 1
            new_case.save()
            return HttpResponseRedirect("/mysite/support/")
    supportcategory = SupportPlanCategory.objects.filter(active=True)
    return render(request, template_name, {'supportcategory': supportcategory})


@login_required
def support_detail(request, case_id):
    template_name = "myadmin/support/support_detail.html"
    supportcase = None
    try:
        supportcase = SupportCases.objects.get(id=case_id, user=request.user)
    except:
        return HttpResponseRedirect("/mysite/support/")
    return render(request, template_name, {'supportcase': supportcase})


@login_required
def support_reopen(request, case_id):
    template_name = "myadmin/support/support_reopen.html"
    if request.method == "POST":
        comment = request.POST.get("comment")
        supportcasedetail = SupportCasesDetail(supportcases_id=case_id, user=request.user, comment=comment)
        supportcasedetail.save()
        supportcasedetail.supportcases.status = 5
        supportcasedetail.supportcases.save()
        return HttpResponseRedirect("/mysite/support/detail/%s/" % (case_id))
    return render(request, template_name, {})

templates/myadmin/support/support_create.html
{% extends "admin_base.html" %}
{% block title %}  Support Create {% endblock %}

{% block content-wrapper %}

  <div class="content-wrapper" style="min-height: 903px;">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        {% if supportcase %} Change {% else %} Create New {% endif %} Case
      </h1>
      <ol class="breadcrumb">
        <li><a href="/mysite/"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="/mysite/support/">My support cases</a></li>
        <li class="active">{% if supportcase %} {{ supportcase.subject }} {% else %} Create New Case{% endif %} </li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="row">
        <!-- right column -->
        <div class="col-md-12">
          <!-- Horizontal Form -->
          <div class="box box-info">
            <div class="box-header with-border">
              <h3 class="box-title">Support Form</h3>
            </div>
            <!-- /.box-header -->
            <!-- form start -->
            <form class="form-horizontal" id="supportcaseform" name="supportcaseform" method="POST" action="{% if supportcase %}/mysite/support/change/{{ supportcase.id }}/{% else %}/mysite/support/create/{% endif %}">
                {% csrf_token %}
              <div class="box-body">
                <div class="form-group">
                  <div class="col-sm-offset-3 col-sm-9">
                    <span class="error-message error" style="display:none">

                    </span>
                  </div>
                </div>

                 <div class="form-group">
                  <label class="col-sm-3 control-label" for="from_name">Regarding</label>
                  <div class="col-sm-9">
                    <select class="form-control" id="supportcategory" name="supportcategory" required>
                    {% for s in supportcategory %}
                    <option value="{{ s.id }}" {% ifequal s.id supportcase.supportcategory.id %} selected="selected" {% endifequal %}>{{ s.name }}</option>
                    {% endfor %}
                  </select>                  
                   </div>
                </div>
             
                <div class="form-group">
                  <label class="col-sm-3 control-label" for="name">Subject</label>
                  <div class="col-sm-9">
                   <input type="text" placeholder="Subject" id="subject" name="subject" class="form-control" value="{{ supportcase.subject }}" required>
                  </div>
                </div>
                <div class="form-group">
                  <label class="col-sm-3 control-label" for="name">Description</label>
                  <div class="col-sm-9">
                    <textarea name="description" id="description" rows=10 style="width:100%" required></textarea>
                  </div>
                </div>
              </div>
              <!-- /.box-body -->
              <div class="box-footer">
                <button class="btn btn-default" type="reset">Reset</button>
                <button class="btn btn-info pull-right" type="submit" id="sender_button">Submit</button>
              </div>
              <!-- /.box-footer -->
            </form>
          </div>
          <!-- /.box -->
        </div>
        <!--/.col (right) -->
      </div>
      <!-- /.row -->
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->

{% endblock %}

templates/myadmin/support/support_detail.html
{% extends "admin_base.html" %}
{% load staticfiles %}
{% block title %} Support Detail {% endblock %}
 {% block content-wrapper %}

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Case Details
      </h1>
      <ol class="breadcrumb">
        <li><a href="/mysite/"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="/support/">support</a></li>
        <li class="active">Case Details</li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">

      <div class="row">
        <div class="col-md-5">

          <!-- Profile Image -->
          <div class="box box-primary">
            <div class="box-body box-profile">
             
              <p class="text-muted text-center">Support Plan : Basic </p>
              <ul class="list-group list-group-unbordered">
                <li class="list-group-item">
                  <b>Case ID</b> <span class="pull-right">{{ supportcase.id }}</span>
                </li>
                <li class="list-group-item">
                  <b>Status</b> <span class="pull-right">{{ supportcase.get_status_display }}</span>
                </li>
                <li class="list-group-item">
                  <b>Severity</b> <span class="pull-right">{{ supportcase.get_severity_display }}</span>
                </li>
               <li class="list-group-item">
                  <b>Created</b> <span class="pull-right">{{ supportcase.date }}</span>
                </li>
               <li class="list-group-item">
                  <b>Category</b> <span class="pull-right">{{ supportcase.supportcategory.name }}</span>
                </li>
               <li class="list-group-item">
                  <b>Subject</b> <span class="pull-right">{{ supportcase.subject }}</span>
                </li>  
              </ul>
             
               {% if supportcase.status == 3 or supportcase.status == 4 %}
             <br><br>
              <a href="/mysite/support/reopen/{{ supportcase.id }}/" class="btn btn-primary btn-block"><b>Reopen Case</b></a>
             
               {% endif %}
             
            </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->
        </div>
        <!-- /.col -->
        <div class="col-md-7">
         <div class="nav-tabs-custom">
<div class="tab-content">
           <div id="timeline" class="tab-pane active">
          <ul class="timeline timeline-inverse">
            <!-- timeline time label -->
            <li class="time-label">
                  <span class="bg-red">
                    {{ supportcase.date|date:"D d M Y" }}
                  </span>
            </li>
            <!-- /.timeline-label -->
            <!-- timeline item -->
            <li>
              <i class="fa fa-envelope bg-blue"></i>

              <div class="timeline-item">
                <span class="time"><i class="fa fa-clock-o"></i> {{ supportcase.date|time:"H:i" }}</span>

                <h3 class="timeline-header"><a href="#">{% if supportcase.user.first_name %} {{ supportcase.user.first_name }} {% else %}{{ supportcase.user.username }} {% endif %}</a> </h3>

                <div class="timeline-body">
                 {{ supportcase.description|safe }}
                </div>
                
              </div>
            </li>
           {% for s in supportcase.supportcasesdetail_set.all %}
            <!-- timeline time label -->
            <li class="time-label">
                  <span class="bg-green">
                    {{ s.modified_date|date:"D d M Y" }}
                  </span>
            </li>
            <!-- /.timeline-label -->
           
            <!-- timeline item -->
            <li>
              <i class="fa fa-comments bg-yellow"></i>

              <div class="timeline-item">
                <span class="time"><i class="fa fa-clock-o"></i> {{ s.modified_date|time:"H:i" }}</span>

                <h3 class="timeline-header"><a href="#">{% if s.user.first_name %} {{ s.user.first_name }} {% else %}{{ s.user.username }} {% endif %}</a></h3>

                <div class="timeline-body">
                 {{ s.comment|safe }}
                </div>
                
              </div>
            </li>
            <!-- END timeline item -->
           {% endfor %}
            
           <li>
                    <i class="fa fa-clock-o bg-gray"></i>
                  </li>
          </ul>
            </div>
         </div>
</div>
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->

    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
{% endblock %}

templates/myadmin/support/support_reopen.html
{% extends "admin_base.html" %}
 {% block title %}  Support Reopen {% endblock %}

{% block content-wrapper %}

  <div class="content-wrapper" style="min-height: 903px;">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
         Reopen Case
      </h1>
      <ol class="breadcrumb">
        <li><a href="/mysite/"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="/mysite/support/">My support case</a></li>
        <li class="active">Reopen </li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="row">
        <!-- right column -->
        <div class="col-md-12">
          <!-- Horizontal Form -->
          <div class="box box-info">
            <div class="box-header with-border">
              <h3 class="box-title">Support Case Reopen Form</h3>
            </div>
            <!-- /.box-header -->
            <!-- form start -->
            <form class="form-horizontal" name="supportcasereopenform" method="POST" action="">
                {% csrf_token %}
              <div class="box-body">
                <div class="form-group">
                  <div class="col-sm-offset-3 col-sm-9">
                    <span class="error-message error" style="display:none">

                    </span>
                  </div>
                </div> 
                
                <div class="form-group">
                  <label class="col-sm-3 control-label" for="name">Reply</label>
                  <div class="col-sm-9">
                    <textarea name="comment" id="comment" rows=10 style="width:100%" required></textarea>
                  </div>
                </div>
              </div>
              <!-- /.box-body -->
              <div class="box-footer">
                <button class="btn btn-default" type="reset">Reset</button>
                <button class="btn btn-info pull-right" type="submit" id="sender_button">Submit</button>
              </div>
              <!-- /.box-footer -->
            </form>
          </div>
          <!-- /.box -->
        </div>
        <!--/.col (right) -->
      </div>
      <!-- /.row -->
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->

{% endblock %}